#!/usr/bin/env bash

set -euo pipefail

(
  echo "// This file was generated by 'update-numbers.bash'";
  echo 'export const data = `';

  CLIENT='2021-resident-visa-netlify-app'
  CLIENT_URL='https://2021-resident-visa.netlify.app/'
  curl -v 'https://www.immigration.govt.nz/new-zealand-visas/waiting-for-a-visa/how-long-it-takes-to-process-your-visa-application/2021-resident-visa-processing-times' \
      -H "User-Agent: $CLIENT/2 ($CLIENT_URL)" \
    | grep -oP '(?<=^<p>)([\d,]+|\d+ \w+ \d{4})(?=</p>$)';

  echo '`;';
) > src/lib/data/processing-data.js;
