#!/usr/bin/env bash

# Requirements: pdftotext on the PATH (https://packages.ubuntu.com/focal/utils/poppler-utils)

set -euo pipefail

(
  echo "// This file was generated by 'update-numbers.bash'";
  echo 'export const data = `';

  CLIENT='2021-resident-visa-netlify-app'
  CLIENT_URL='https://2021-resident-visa.netlify.app/'
  curl -v 'https://www.immigration.govt.nz/documents/other-resources/2021-resident-visa-processing.pdf' \
      -H "User-Agent: $CLIENT/1 ($CLIENT_URL)" \
    | pdftotext -nopgbrk -layout - - \
    | grep -P '\w+, \w+ \d+\s+[\d.,]+\s+[\d.,]+\s+[\d.,]+\s+[\d.,]+\s+[\d.,]+';

  echo '`;';
) > src/lib/data/processing-data.js;