name: Update processing numbers

on:
  workflow_dispatch: ~
  schedule:
    - cron: '23 * * * 4-6' # Every hour on the 23rd minute, Thu-Sat

jobs:
  update_numbers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Update processing numbers
        run: |
          ./update-numbers.bash
      - name: Commit any changes
        run: |
          set -euo pipefail

          git status
          git diff

          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          if git diff --output-indicator-new=N --output-indicator-old=O -- src/lib/data/processing-data.js | grep -P '^N' \
            && ! git diff --output-indicator-new=N --output-indicator-old=O -- src/lib/data/processing-data.js | grep -P '^O'
          then
            git add src/lib/data/processing-data.js
            git commit -m "New processing data ($(date +'%a, %b %e %Y' | sed -r 's#\s+# #g'))"
            git push
          else
            echo 'Nothing to commit, or there are deletions'
          fi
